# Runs every case in tools\test\cases on the native (PC) build, several at a time, and saves the results:
#   tools\test\run-native-all.ps1 [-Filter 'mq-*','bug-*'] [-Jobs 8] [-Data out\world] [-Start 'Seyda Neen'] [-Wait 600] [-Build]
#                                  [-IgnoreWarnings]  monitor warnings (floors, textures, memory ...) do not fail a case;
#                                                     failed expectations, driver failures and runs that die still do
# -> build\native-results\<stamp>\{summary.txt, results.csv, logs\<case>.log, out\<case>.txt}; the newest run is also
#    copied to build\native-results\latest\.  chain-* cases (generated by run-suite -Chained, each needs the one
#    before it) are left out unless named in -Filter.
# Each case gets its own SD folder (build\native\sd-<slot>), so they do not touch each other's logs or saves.
# -Exe / -SdRoot / -NoLatest: another native build (build.py with MW3DS_NATIVE_BUILD), its own SD folders, and no copy
# to build\native-results\latest (a second session's run that leaves the first one's alone)
param([string[]]$Filter = @(), [int]$Jobs = 0, [string]$Data = 'out\world', [string]$Start = 'Seyda Neen', [int]$Wait = 600,
      [switch]$Build, [switch]$IgnoreWarnings, [string]$Exe = '', [string]$SdRoot = 'build\native', [switch]$NoLatest)
$root = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
if ($Jobs -le 0) { $Jobs = [Math]::Max(1, [Environment]::ProcessorCount - 2) }
if (-not $Exe -and ($Build -or -not (Test-Path (Join-Path $root 'build\native\mw3ds-native.exe')))) {
    python (Join-Path $PSScriptRoot 'native\build.py')
    if ($LASTEXITCODE -ne 0) { "native build failed"; exit 1 }
}
# The binary as it is now: a rebuild during the run must not change what the cases run
$exe = if ($Exe) { (Resolve-Path $Exe).Path } else { Join-Path $root 'build\native\mw3ds-native.exe' }

$Filter = @($Filter | ForEach-Object { $_ -split ',' } | Where-Object { $_ })     # (-File passes a,b as one string)
$cases = Get-ChildItem (Join-Path $root 'tools\test\cases\*.txt') | ForEach-Object { $_.BaseName }
if ($Filter) {
    $cases = $cases | Where-Object { $n = $_; $Filter | Where-Object { $n -like $_ } }
} else {
    # (chain-*: made by run-suite -Chained; zz-open-*: known open bugs, run by name)
    $cases = $cases | Where-Object { $_ -notlike 'chain-*' -and $_ -notlike 'zz-open-*' }
}
$cases = @($cases | Sort-Object)
if (-not $cases) { "no cases match"; exit 1 }

$stamp = Get-Date -Format 'yyyyMMdd-HHmmss'
$resDir = Join-Path $root "build\native-results\$stamp"
$logDir = Join-Path $resDir 'logs'
$outDir = Join-Path $resDir 'out'
New-Item -ItemType Directory -Force $logDir, $outDir | Out-Null

$slots = @(for ($i = 0; $i -lt $Jobs; $i++) { @{ id = $i; proc = $null; case = $null; started = $null } })
$rows = New-Object System.Collections.ArrayList
$queue = New-Object System.Collections.Queue
$cases | ForEach-Object { $queue.Enqueue($_) }
$total = $cases.Count
$clock = [Diagnostics.Stopwatch]::StartNew()

function Finish($slot) {
    $case = $slot.case
    $txt = Join-Path $outDir "$case.txt"
    $out = if (Test-Path $txt) { @(Get-Content $txt) } else { @() }
    $verdict = @($out | Where-Object { $_ -like 'RESULT:*' }) | Select-Object -First 1
    if (-not $verdict) { $verdict = 'RESULT: FAIL (no result: the run died or timed out)' }
    $sdLog = Join-Path $root "$SdRoot\sd-$($slot.id)\3ds\mw3ds\log.txt"
    if (Test-Path $sdLog) { Copy-Item $sdLog (Join-Path $logDir "$case.log") -Force }
    $pass = $verdict -like 'RESULT: PASS*'
    $warn = if ($verdict -match '(\d+) monitor warnings') { [int]$Matches[1] } else { 0 }
    if (-not $pass -and $IgnoreWarnings -and $verdict -match '^RESULT: FAIL \(\d+ expectations met, 0 failed, 0 driver failures, \d+ monitor warnings(\)|;)') { $pass = $true }
    $detail = $verdict -replace '^RESULT: (PASS|FAIL) ?', ''
    # Sweep batches (qrun / srun / xrun) try each quest's opener and are judged by how many quests started
    # (questrun.py --check), not by RESULT: a "topic not offered" there is a finding about that quest. A batch passes
    # when it starts at least as many quests as the emulator sweep did (build\<prefix>-results.txt), else when none fail.
    if ($case -match '^(qrun|srun|xrun)-\d+$') {
        $warn = 0
        $check = @(python (Join-Path $PSScriptRoot 'questrun.py') --check $case --log (Join-Path $logDir "$case.log") 2>&1)
        Set-Content (Join-Path $logDir "$case.check.txt") $check
        $mine = $check | Where-Object { $_ -match "^${case}: (\d+) started, (\d+) not" } | Select-Object -Last 1
        if ($mine -match ': (\d+) started, (\d+) not') {
            $started = [int]$Matches[1]; $not = [int]$Matches[2]
            $base = $null
            $baseFile = Join-Path $root "build\$($case -replace '-\d+$', '')-results.txt"
            if (Test-Path $baseFile) {
                $b = Select-String -Path $baseFile -Pattern "^${case}: (\d+) started, (\d+) not" | Select-Object -Last 1
                if ($b) { $base = [int]$b.Matches[0].Groups[1].Value }
            }
            $pass = if ($null -ne $base) { $started -ge $base } else { $not -eq 0 }
            $detail = "sweep: $started started, $not not" + $(if ($null -ne $base) { " (emulator sweep: $base started)" } else { ' (no emulator baseline)' })
        } else {
            $pass = $false
            $detail = 'sweep: no check result (' + (($check | Select-Object -Last 1) -as [string]) + ')'
        }
    }
    [void]$rows.Add([pscustomobject]@{ case = $case; result = $(if ($pass) { 'PASS' } else { 'FAIL' }); warnings = $warn
        seconds = [int]((Get-Date) - $slot.started).TotalSeconds; detail = $detail })
    "{0,4}/{1}  {2,-4}  {3}" -f $rows.Count, $total, $(if ($pass) { 'PASS' } else { 'FAIL' }), $case
    $slot.proc = $null
}

while ($queue.Count -gt 0 -or @($slots | Where-Object { $_.proc }).Count -gt 0) {
    foreach ($slot in $slots) {
        if ($slot.proc -and $slot.proc.HasExited) { Finish $slot }
        if (-not $slot.proc -and $queue.Count -gt 0) {
            $case = $queue.Dequeue()
            $slot.case = $case
            $slot.started = Get-Date
            $sd = Join-Path $root "$SdRoot\sd-$($slot.id)"
            $args = @('-NoProfile', '-File', (Join-Path $PSScriptRoot 'run-test.ps1'), $case, '-Native', '-Sd', $sd,
                      '-Data', $Data, '-Start', ('"' + $Start + '"'), '-Wait', $Wait, '-Exe', $exe)
            $slot.proc = Start-Process powershell -ArgumentList $args -PassThru -WindowStyle Hidden `
                -RedirectStandardOutput (Join-Path $outDir "$case.txt") -RedirectStandardError (Join-Path $outDir "$case.err")
        }
        if ($slot.proc -and ((Get-Date) - $slot.started).TotalSeconds -gt $Wait + 60) {
            $slot.proc.Kill()
        }
    }
    Start-Sleep -Milliseconds 300
}

$rows | Sort-Object case | Export-Csv (Join-Path $resDir 'results.csv') -NoTypeInformation
$passed = @($rows | Where-Object { $_.result -eq 'PASS' } | Sort-Object case)
$failed = @($rows | Where-Object { $_.result -eq 'FAIL' } | Sort-Object case)
$mode = if ($IgnoreWarnings) { ', monitor warnings ignored' } else { '' }
$lines = @("native run ${stamp}: $($passed.Count) of $total passed in $([int]$clock.Elapsed.TotalSeconds) s ($Jobs at a time, data $Data$mode)")
$lines += ''
$lines += "SUCCEEDED ($($passed.Count)):"
$lines += $passed | ForEach-Object { "  $($_.case)" + $(if ($_.detail -like 'sweep:*') { "  $($_.detail)" } elseif ($_.warnings) { "  ($($_.warnings) warnings ignored)" } else { '' }) }
if ($failed) { $lines += ''; $lines += "FAILED ($($failed.Count)):"; $lines += $failed | ForEach-Object { "  $($_.case)  $($_.detail)" } }
Set-Content (Join-Path $resDir 'summary.txt') $lines
if (-not $NoLatest) {
    $latest = Join-Path $root 'build\native-results\latest'
    if (Test-Path $latest) { Remove-Item $latest -Recurse -Force }
    Copy-Item $resDir $latest -Recurse
}
''
$lines
"saved: $resDir"
